app3/urls.py
from django.urls import path
from app3 import views
app_name="app3"


urlpatterns = [
    path('trail/',views.trails,name="trail"),
    path('profile/',views.profile,name="profile"),
]

partials/urls.py
from django.contrib import admin
from django.urls import path,include
import app3
from app3 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',views.base,name='base'),
    path('',views.home,name='home'),
    path('app3/',include("app3.urls")),
]

app3/models.py
from django.db import models

# Create your models here.

app3/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def trails(request):
    return HttpResponse("<h1>project is on air</h1>")

def base(request):
    return render(request,"base.html")

def home(request):
    return render(request,"app3/home.html")

def profile(request):
    name="rocky"
    return render(request,"app3/profile.html",{'name':name})

templates/app3/home.html
{% extends "base.html" %}

{% block  title %}
 <title>home page</title>
{% endblock  %}

{% block  content %}
  <div class="container">
      <div class="jumbotron">
          <center><h1>WELCOME TO HOMEPAGE</h1></center>
      </div>
  </div>
{% endblock  %}

templates/app3/profile.html
{% extends "base.html" %}


{% block title %}
  <title>profile page</title>
{% endblock  %}


{% block content %}
<div class="container">
    <div class="jumbotron">
        <center><h1>welcome to {{name}} profile page</h1></center>
    </div>
</div>
  
{% endblock  %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>base</title>
    {% endblock  %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    
</head>
<body>
   {% include "partials/_header.html"%}
   {% include "partials/_navbar.html"%}


    

    {% block  content %}
    <div class="container">
        <div class="jumbotron">
            <center><h1>WELCOME TO basePAGE</h1></center>
        </div>
    </div>
    {% endblock  %}
    {% include "partials/_footer.html"%}


    
    
</body>
</html>

templates/partials/_footer.html
<div class="alert alert-primary" role="alert">
    <center>footer</center>
</div>

templates/partials/_header.html
<div class="alert alert-secondary" role="alert">
    <center>header</center>
</div>

templates/partials/_navbar.html
<div class="container">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'home' %}">home</a>
        </li>
        <li  class="nav-item">
            <a class="nav-link" href="{% url 'app3:profile'%}">profile</a>
        </li>
    </ul>
</div>